@extends('layout.main')
@section('title', 'Panel de avisos de salida')
@push('styles')
<style>
.departure-dashboard{color:#263238}.departure-hero{padding:1.4rem 1.5rem;border-radius:1rem;color:#fff;background:linear-gradient(125deg,#212529,#455a64);box-shadow:0 12px 30px rgba(20,30,40,.18)}.departure-hero p{color:rgba(255,255,255,.72)}.departure-card{height:100%;padding:1.15rem;background:#fff;border:1px solid rgba(38,50,56,.08);border-radius:.9rem;box-shadow:0 8px 24px rgba(20,30,40,.07)}.departure-kpi span{display:grid;place-items:center;width:2.5rem;height:2.5rem;border-radius:.7rem;color:#fff;background:#263238}.departure-kpi small{display:block;margin-top:.8rem;color:#78909c;font-weight:700}.departure-kpi strong{display:block;color:#263238;font-size:1.8rem;line-height:1.1}.departure-kpi p{margin:.35rem 0 0;color:#90a4ae;font-size:.76rem}.departure-panel h2{margin:0;color:#263238;font-size:1rem;font-weight:800}.departure-panel header p{margin:.2rem 0 0;color:#90a4ae;font-size:.78rem}.departure-chart{height:285px;margin-top:1rem}.departure-alert{padding:.85rem;border:1px solid #e5eaed;border-radius:.75rem}.departure-alert.overdue{border-left:4px solid #dc3545;background:#fff8f8}.departure-alert.active{border-left:4px solid #e0a800}.departure-meta{color:#78909c;font-size:.75rem}.departure-table th{color:#78909c;font-size:.69rem;text-transform:uppercase}.departure-table td{color:#455a64;font-size:.8rem;vertical-align:middle}.departure-status{display:inline-flex;padding:.3rem .55rem;border-radius:999px;font-size:.7rem;font-weight:800}.departure-status.open{background:#fff3cd;color:#856404}.departure-status.closed{background:#d1e7dd;color:#0f5132}@media(max-width:767.98px){.departure-hero{padding:1.1rem}.departure-chart{height:235px}}
</style>
@endpush
@section('content')
<div class="departure-dashboard">
<section class="departure-hero d-flex flex-column flex-lg-row justify-content-between align-items-lg-center gap-3 mb-4"><div><span class="badge bg-warning text-dark mb-2">Prevención y seguimiento</span><h1 class="h3 text-white mb-1">Avisos de salida</h1><p class="mb-0">Visión operativa de las personas y grupos que realizan actividades al aire libre.</p></div><a href="{{ route('aviso.list') }}" class="btn btn-warning mb-0"><i class="fa-solid fa-list-check me-2"></i>Administrar avisos</a></section>
<div class="row g-3 mb-4">
@foreach([['person-hiking','Avisos este año',$metrics['year_total'],'Registros recibidos'],['location-dot','Salidas activas',$metrics['active'],'Grupos en seguimiento'],['triangle-exclamation','Retornos vencidos',$metrics['overdue'],'Requieren verificación'],['people-group','Personas en terreno',$metrics['people_active'],'Participantes activos'],['users','Participantes acumulados',$metrics['participants'],'Durante '.now()->year],['clock','Duración promedio',$metrics['avg_duration']!==null?$metrics['avg_duration'].' h':'S/I','Avisos finalizados']] as [$icon,$label,$value,$copy])<div class="col-6 col-xl-2"><article class="departure-card departure-kpi"><span><i class="fa-solid fa-{{ $icon }}"></i></span><small>{{ $label }}</small><strong>{{ $value }}</strong><p>{{ $copy }}</p></article></div>@endforeach
</div>
<div class="row g-3 mb-4"><div class="col-xl-7"><section class="departure-card departure-panel"><header><h2>Evolución de avisos</h2><p>Registros recibidos durante los últimos ocho meses.</p></header><div class="departure-chart"><canvas id="departuresChart"></canvas></div></section></div><div class="col-xl-5"><section class="departure-card departure-panel"><header><h2>Actividades declaradas</h2><p>Distribución de las disciplinas practicadas.</p></header><div class="departure-chart"><canvas id="activitiesChart"></canvas></div></section></div></div>
<div class="row g-3 mb-4">
<div class="col-lg-5"><section class="departure-card departure-panel"><header><h2>Salidas que requieren seguimiento</h2><p>Activas, ordenadas por fecha prevista de retorno.</p></header><div class="d-grid gap-2 mt-3">@forelse($activeRecords->take(6) as $departure)@php($overdue=Carbon\Carbon::parse($departure->return_date)->isPast())<article class="departure-alert {{ $overdue?'overdue':'active' }}"><div class="d-flex justify-content-between gap-2"><strong>{{ $departure->name }} {{ $departure->lastname }}</strong><span class="badge {{ $overdue?'bg-danger':'bg-warning text-dark' }}">{{ $overdue?'Vencido':'Activo' }}</span></div><div class="departure-meta mt-1"><i class="fa-solid fa-mountain-sun me-1"></i>{{ $departure->destination }} · {{ $departure->number_participants }} participantes</div><div class="departure-meta"><i class="fa-regular fa-clock me-1"></i>Retorno: {{ Carbon\Carbon::parse($departure->return_date)->format('d/m/Y H:i') }}</div></article>@empty<div class="text-center text-muted py-5">No hay salidas activas.</div>@endforelse</div></section></div>
<div class="col-lg-4"><section class="departure-card departure-panel"><header><h2>Avisos por región</h2><p>Concentración geográfica durante el año.</p></header><div class="departure-chart"><canvas id="regionsChart"></canvas></div></section></div>
<div class="col-lg-3"><section class="departure-card departure-panel"><header><h2>Destinos frecuentes</h2><p>Lugares con más avisos.</p></header><div class="mt-3">@forelse($topDestinations as $destination=>$count)<div class="d-flex justify-content-between align-items-center py-2 border-bottom"><span class="small fw-semibold">{{ $destination }}</span><span class="badge bg-dark">{{ $count }}</span></div>@empty<p class="text-muted small">Sin datos disponibles.</p>@endforelse</div><div class="rounded bg-light p-3 mt-4"><small class="text-muted">Tasa de cierre anual</small><strong class="d-block fs-3">{{ $metrics['completion_rate'] }}%</strong><div class="progress" style="height:6px"><div class="progress-bar bg-success" style="width:{{ $metrics['completion_rate'] }}%"></div></div></div></section></div>
</div>
<section class="departure-card departure-panel"><header class="d-flex justify-content-between align-items-center"><div><h2>Actividad reciente</h2><p>Últimos avisos registrados.</p></div><a href="{{ route('aviso.list') }}" class="btn btn-sm btn-outline-dark mb-0">Ver todos</a></header><div class="table-responsive mt-3"><table class="table departure-table mb-0"><thead><tr><th>Salida</th><th>Responsable</th><th>Actividad</th><th>Destino / ruta</th><th>Participantes</th><th>Retorno</th><th>Estado</th></tr></thead><tbody>@forelse($recent as $departure)<tr><td>{{ Carbon\Carbon::parse($departure->departure_date)->format('d/m/Y H:i') }}</td><td><strong>{{ $departure->name }} {{ $departure->lastname }}</strong></td><td>{{ $activityLabels[(int)$departure->activity]??'Sin informar' }}</td><td><strong>{{ $departure->destination }}</strong><div class="text-muted small">{{ $departure->route }}</div></td><td>{{ $departure->number_participants }}</td><td>{{ Carbon\Carbon::parse($departure->return_date)->format('d/m/Y H:i') }}</td><td><span class="departure-status {{ $departure->active?'open':'closed' }}">{{ $departure->active?'Activo':'Finalizado' }}</span></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-5">No hay avisos registrados.</td></tr>@endforelse</tbody></table></div></section>
</div>
@endsection
@push('script')
<script>
document.addEventListener('DOMContentLoaded',()=>{Chart.defaults.color='#667c86';const palette=['#263238','#EA4E1A','#176985','#e0a800','#607d8b','#2e7d32','#8e44ad','#90a4ae'];const common={responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom',labels:{usePointStyle:true,boxWidth:8}}}};new Chart(document.getElementById('departuresChart'),{type:'line',data:{labels:@json($monthLabels),datasets:[{label:'Avisos',data:@json($departureSeries),borderColor:'#EA4E1A',backgroundColor:'rgba(234,78,26,.12)',fill:true,tension:.35,pointRadius:4}]},options:{...common,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,ticks:{precision:0}},x:{grid:{display:false}}}}});new Chart(document.getElementById('activitiesChart'),{type:'doughnut',data:{labels:@json($activities->keys()),datasets:[{data:@json($activities->values()),backgroundColor:palette,borderWidth:0}]},options:{...common,cutout:'62%'}});new Chart(document.getElementById('regionsChart'),{type:'bar',data:{labels:@json($regions->keys()),datasets:[{data:@json($regions->values()),backgroundColor:'#176985',borderRadius:6}]},options:{...common,indexAxis:'y',plugins:{legend:{display:false}},scales:{x:{beginAtZero:true,ticks:{precision:0}},y:{grid:{display:false}}}}});});
</script>
@endpush
