version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8001:8001"
    depends_on:
      - mysql
    tty: true
    command: php artisan serve --host=0.0.0.0 --port=8001
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpass
    ports:
      - "3306:3306"  
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
